name: Go But With Current Dependencies

on:
  schedule:
    - cron: '51 11 * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Dependencies
      run: 'sudo apt-get update && sudo apt-get -y install graphviz libasound2-dev libgl-dev libgles-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev xvfb'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.19'
        check-latest: true

    - name: Remove Module Replacements
      run: 'sed -i -e "s,^replace ,//replace ," go.mod'

    - name: Update
      run: 'make mod-update'

    - name: Build
      run: 'AAAAXY_BUILD_USE_VERSION_FILE=true AAAAXY_GENERATE_ASSETS=true AAAAXY_DIFF_ASSETS=true make'

    - name: Vet
      run: 'make vet'

    - name: Test
      run: 'xvfb-run sh scripts/regression-test-demo.sh linux-amd64 "on track for Any%, All Paths, No Teleports and No Coil" ./aaaaxy assets/demos/benchmark.dem'

    - name: Archive Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: regression-test-results-benchmark-linux-amd64
        path: |
          *.dem.*.log
          *.dem.*.png

